### ISSUE TITLE
mc-utils: Failure when deploying for lx2160acex7

### ISSUE THREAD

**Issue by Ossanes** [Freescale/meta-freescale-3rdparty#175]
image: core-image-minimal
machine: lx2160acex7
distro: fslc-framebuffer
branch: master

ERROR: mc-utils-git-r0 do_deploy: ExecutionError('/home/aquino/src/tests/build/tmp/work/lx2160acex7-fslc-linux/mc-utils/git-r0/temp/run.do_deploy.2237593', 1, None, None)
Log data follows:                                    
| DEBUG: Executing python function sstate_task_prefunc                                                                                                                                                              
| DEBUG: Python function sstate_task_prefunc finished                                                                                            
| DEBUG: Executing shell function do_deploy                                                                                                                                                                         
| cp: cannot stat '/home/aquino/src/tests/build/tmp/work/lx2160acex7-fslc-linux/mc-utils/git-r0/image/boot/mc-utils/*': No such file or directory

@rehsack

**Comment by angolini** [comment]
I'm closing this issue as it's not updated since 4 moths ago. Please reopen when/if needed.

**Comment by rehsack** [comment]
I'm making serious progress getting my environment back working, but Q2/22 seems more likely than Q1.

I will send PR's once I come to lx2 platform :)
