### ISSUE TITLE
nitrogen8mp: Error when compiling imx-boot

### ISSUE THREAD

**Issue by Ossanes** [Freescale/meta-freescale-3rdparty#179]
Build Configuration:
BB_VERSION           = "1.53.0"
BUILD_SYS            = "x86_64-linux"
NATIVELSBSTRING      = "universal"
TARGET_SYS           = "aarch64-fslc-linux"
MACHINE              = "nitrogen8mp"
DISTRO               = "fslc-framebuffer"

ERROR: Nothing PROVIDES 'imx-boot' (but /home/aquino/src/tests/sources/poky/meta/recipes-core/images/core-image-minimal.bb DEPENDS on or otherwise requires it)
imx-boot was skipped: incompatible with machine nitrogen8mp (not in COMPATIBLE_MACHINE)

@chrisdimich

**Comment by chrisdimich** [comment]
Using the same MACHINE and DISTRO I am able to build imx-boot just fine on master. Do you have any more information you can provide?

**Comment by otavio** [comment]
@Ossanes can you re-test?

**Comment by angolini** [comment]
Close due to inactivity.
