### ISSUE TITLE
linux-boundary on mickledore

### ISSUE THREAD

**Issue by durje** [Freescale/meta-freescale-3rdparty#255]
The linux-boundary recipe does not build on the current master branch.

RROR: linux-boundary-5.15.71+gitAUTOINC+b2f34070b1-r0 do_compile_kernelmodules: oe_runmake failed
ERROR: linux-boundary-5.15.71+gitAUTOINC+b2f34070b1-r0 do_compile_kernelmodules: ExecutionError('/home/user/Projects/yocto/yocto-tmp/work/nitrogen6x-fslc-linux-gnueabi/linux-boundary/5.15.71+gitAUTOINC+b2f34070b1-r0/temp/run.do_compile_kernelmodules.2959239', 1, None, None)
ERROR: Logfile of failure stored in: /home/user/Projects/yocto/yocto-tmp/work/nitrogen6x-fslc-linux-gnueabi/linux-boundary/5.15.71+gitAUTOINC+b2f34070b1-r0/temp/log.do_compile_kernelmodules.2959239
Log data follows:
| DEBUG: Executing shell function do_compile_kernelmodules
| NOTE: KBUILD_BUILD_TIMESTAMP: Fri Jan 13 22:14:43 UTC 2023
| NOTE: make CC=arm-fslc-linux-gnueabi-gcc  -mno-thumb-interwork -marm -fuse-ld=bfd -fmacro-prefix-map=/home/user/Projects/yocto/yocto-tmp/work/nitrogen6x-fslc-linux-gnueabi/linux-boundary/5.15.71+gitAUTOINC+b2f34070b1-r0/git=/usr/src/debug/linux-boundary/5.15.71+gitAUTOINC+b2f34070b1-r0  -fdebug-prefix-map=/home/user/Projects/yocto/yocto-tmp/work/nitrogen6x-fslc-linux-gnueabi/linux-boundary/5.15.71+gitAUTOINC+b2f34070b1-r0/git=/usr/src/debug/linux-boundary/5.15.71+gitAUTOINC+b2f34070b1-r0  -fmacro-prefix-map=/home/user/Projects/yocto/yocto-tmp/work/nitrogen6x-fslc-linux-gnueabi/linux-boundary/5.15.71+gitAUTOINC+b2f34070b1-r0/build=/usr/src/debug/linux-boundary/5.15.71+gitAUTOINC+b2f34070b1-r0  -fdebug-prefix-map=/home/user/Projects/yocto/yocto-tmp/work/nitrogen6x-fslc-linux-gnueabi/linux-boundary/5.15.71+gitAUTOINC+b2f34070b1-r0/build=/usr/src/debug/linux-boundary/5.15.71+gitAUTOINC+b2f34070b1-r0  -fdebug-prefix-map=/home/user/Projects/yocto/yocto-tmp/work/nitrogen6x-fslc-linux-gnueabi/linux-boundary/5.15.71+gitAUTOINC+b2f34070b1-r0/recipe-sysroot=  -fmacro-prefix-map=/home/user/Projects/yocto/yocto-tmp/work/nitrogen6x-fslc-linux-gnueabi/linux-boundary/5.15.71+gitAUTOINC+b2f34070b1-r0/recipe-sysroot=  -fdebug-prefix-map=/home/user/Projects/yocto/yocto-tmp/work/nitrogen6x-fslc-linux-gnueabi/linux-boundary/5.15.71+gitAUTOINC+b2f34070b1-r0/recipe-sysroot-native=  -fdebug-prefix-map=/home/user/Projects/yocto/yocto-tmp/work-shared/nitrogen6x/kernel-source=/usr/src/kernel -fdebug-prefix-map=/home/user/Projects/yocto/yocto-tmp/work-shared/nitrogen6x/kernel-build-artifacts=/usr/src/kernel LD=arm-fslc-linux-gnueabi-ld.bfd   OBJCOPY=arm-fslc-linux-gnueabi-objcopy  HOSTCC=gcc  HOSTCFLAGS=-isystem/home/user/Projects/yocto/yocto-tmp/work/nitrogen6x-fslc-linux-gnueabi/linux-boundary/5.15.71+gitAUTOINC+b2f34070b1-r0/recipe-sysroot-native/usr/include -O2 -pipe HOSTLDFLAGS=-L/home/user/Projects/yocto/yocto-tmp/work/nitrogen6x-fslc-linux-gnueabi/linux-boundary/5.15.71+gitAUTOINC+b2f34070b1-r0/recipe-sysroot-native/usr/lib                         -L/home/user/Projects/yocto/yocto-tmp/work/nitrogen6x-fslc-linux-gnueabi/linux-boundary/5.15.71+gitAUTOINC+b2f34070b1-r0/recipe-sysroot-native/lib                         -Wl,--enable-new-dtags                         -Wl,-rpath-link,/home/user/Projects/yocto/yocto-tmp/work/nitrogen6x-fslc-linux-gnueabi/linux-boundary/5.15.71+gitAUTOINC+b2f34070b1-r0/recipe-sysroot-native/usr/lib                         -Wl,-rpath-link,/home/user/Projects/yocto/yocto-tmp/work/nitrogen6x-fslc-linux-gnueabi/linux-boundary/5.15.71+gitAUTOINC+b2f34070b1-r0/recipe-sysroot-native/lib                         -Wl,-rpath,/home/user/Projects/yocto/yocto-tmp/work/nitrogen6x-fslc-linux-gnueabi/linux-boundary/5.15.71+gitAUTOINC+b2f34070b1-r0/recipe-sysroot-native/usr/lib                         -Wl,-rpath,/home/user/Projects/yocto/yocto-tmp/work/nitrogen6x-fslc-linux-gnueabi/linux-boundary/5.15.71+gitAUTOINC+b2f34070b1-r0/recipe-sysroot-native/lib                         -Wl,-O1 -Wl,--allow-shlib-undefined -Wl,--dynamic-linker=/home/user/Projects/yocto/yocto-tmp/sysroots-uninative/x86_64-linux/lib/ld-linux-x86-64.so.2 HOSTCPP=gcc  -E HOSTCXX=g++  HOSTCXXFLAGS=-isystem/home/user/Projects/yocto/yocto-tmp/work/nitrogen6x-fslc-linux-gnueabi/linux-boundary/5.15.71+gitAUTOINC+b2f34070b1-r0/recipe-sysroot-native/usr/include -O2 -pipe PAHOLE=false -C /home/user/Projects/yocto/yocto-tmp/work/nitrogen6x-fslc-linux-gnueabi/linux-boundary/5.15.71+gitAUTOINC+b2f34070b1-r0/build -j 8 modules LOADADDR=0x10008000
| In file included from /home/user/Projects/yocto/yocto-tmp/work-shared/nitrogen6x/kernel-source/include/asm-generic/current.h:5,
|                  from ./arch/arm/include/generated/asm/current.h:1,
|                  from /home/user/Projects/yocto/yocto-tmp/work-shared/nitrogen6x/kernel-source/include/linux/mutex.h:14,
|                  from /home/user/Projects/yocto/yocto-tmp/work-shared/nitrogen6x/kernel-source/include/linux/kernfs.h:12,
|                  from /home/user/Projects/yocto/yocto-tmp/work-shared/nitrogen6x/kernel-source/include/linux/sysfs.h:16,
|                  from /home/user/Projects/yocto/yocto-tmp/work-shared/nitrogen6x/kernel-source/include/linux/kobject.h:20,
|                  from /home/user/Projects/yocto/yocto-tmp/work-shared/nitrogen6x/kernel-source/include/linux/cdev.h:5,
|                  from /home/user/Projects/yocto/yocto-tmp/work-shared/nitrogen6x/kernel-source/drivers/char/magdecode.c:24:
| In function 'check_copy_size',
|     inlined from 'copy_to_user' at /home/user/Projects/yocto/yocto-tmp/work-shared/nitrogen6x/kernel-source/include/linux/uaccess.h:199:6,
|     inlined from 'mag_read' at /home/user/Projects/yocto/yocto-tmp/work-shared/nitrogen6x/kernel-source/drivers/char/magdecode.c:459:9:
| /home/user/Projects/yocto/yocto-tmp/work-shared/nitrogen6x/kernel-source/include/linux/thread_info.h:211:25: error: call to '__bad_copy_from' declared with attribute error: copy source size is too small
|   211 |                         __bad_copy_from();
|       |                         ^~~~~~~~~~~~~~~~~
| make[2]: *** [/home/user/Projects/yocto/yocto-tmp/work-shared/nitrogen6x/kernel-source/scripts/Makefile.build:289: drivers/char/magdecode.o] Error 1
| make[2]: *** Waiting for unfinished jobs....
| make[1]: *** [/home/user/Projects/yocto/yocto-tmp/work-shared/nitrogen6x/kernel-source/scripts/Makefile.build:552: drivers/char] Error 2
| make: *** [/home/user/Projects/yocto/yocto-tmp/work-shared/nitrogen6x/kernel-source/Makefile:1898: drivers] Error 2
| make: *** Waiting for unfinished jobs....
| ERROR: oe_runmake failed
| WARNING: exit code 1 from a shell command.
ERROR: Task (/home/user/Projects/yocto/meta-freescale-3rdparty/recipes-kernel/linux/linux-boundary_5.15.bb:do_compile_kernelmodules) failed with exit code '1'

Build Configuration:
BB_VERSION           = "2.3.1"
BUILD_SYS            = "x86_64-linux"
NATIVELSBSTRING      = "universal"
TARGET_SYS           = "arm-fslc-linux-gnueabi"
MACHINE              = "nitrogen6x"
DISTRO               = "fslc-x11"
DISTRO_VERSION       = "4.1-snapshot-20230403"
TUNE_FEATURES        = "arm vfp cortexa9 neon thumb callconvention-hard"
TARGET_FPU           = "hard"
meta                 
meta-poky            
meta-yocto-bsp       = "master:df3ce81ed3e5491b084041c5bcbd16dada129cf9"
meta-oe              
meta-multimedia      
meta-xfce            
meta-gnome           
meta-python          
meta-networking      = "master:17243e70c8309751a1129a9214899ec476ab121a"
meta-freescale       = "master:c5ebde814cbc67656d2d2c373095a0f1515e1e09"
meta-freescale-distro = "master:a4efa17a9f6b25d8d9290dfee8275059d40b83df"
meta-freescale-3rdparty = "master:6301ad2622761aceda42bdca110168b2fe10198c"

local.conf

MACHINE ??= 'nitrogen6x'
DISTRO ?= 'fslc-x11'

bblayers.conf 

BBLAYERS ?= " \
  /home/user/Projects/yocto/poky/meta \
  /home/user/Projects/yocto/poky/meta-poky \
  /home/user/Projects/yocto/poky/meta-yocto-bsp \
  \
  /home/user/Projects/yocto/meta-openembedded/meta-oe \
  /home/user/Projects/yocto/meta-openembedded/meta-multimedia \
  /home/user/Projects/yocto/meta-openembedded/meta-xfce \
  \
  /home/user/Projects/yocto/meta-openembedded/meta-gnome \
  /home/user/Projects/yocto/meta-openembedded/meta-python \
  /home/user/Projects/yocto/meta-openembedded/meta-networking \
  \
  /home/user/Projects/yocto/meta-freescale \
  /home/user/Projects/yocto/meta-freescale-distro \
  /home/user/Projects/yocto/meta-freescale-3rdparty \
  \
  "

I tried to put all repo on the Kirkstone, but I get lots off "QA Issue: Package version for package XXXX went backwards which would break package feeds" errors.
TARGET_SYS           = "arm-fslc-linux-gnueabi"
MACHINE              = "nitrogen6x"
DISTRO               = "fslc-x11"
DISTRO_VERSION       = "4.0"
TUNE_FEATURES        = "arm vfp cortexa9 neon thumb callconvention-hard"
TARGET_FPU           = "hard"
meta                 
meta-poky            
meta-yocto-bsp       = "kirkstone:407c3e0237d947ec003bdd1af89a226121c7939c"
meta-oe              
meta-multimedia      
meta-xfce            
meta-gnome           
meta-python          
meta-networking      = "kirkstone:9cf4ebeb3de524009a73f49722489dc4aa183adb"
meta-freescale       = "kirkstone:13462033a37f0dd3334794fae85c3fd2663efbef"
meta-freescale-distro = "kirkstone:d5bbb487b2816dfc74984a78b67f7361ce404253"
meta-freescale-3rdparty = "kirkstone:f6fa0fd8783ce69d07feaad0b7ca6759b5a4d5d6"

**Comment by chrisdimich** [comment]
I will take a look. Thanks

**Comment by durje** [comment]
Just checking if you had the chance to take a look at this?
Thanks

**Comment by gibsson** [comment]
This has been addressed in a recent kernel update. Please re-open if you still see this issue.
