### ISSUE TITLE
0001-Add-Olimex-iMX8MP-SOM-EVB-IND.patch does not apply

### ISSUE THREAD

**Issue by JSmitNortech** [Freescale/meta-freescale-3rdparty#306]
The patch contained in **recipes-bsp/u-boot/u-boot-imx/0001-Add-Olimex-iMX8MP-SOM-EVB-IND.patch**  does not apply successfully on the Kconfig file in **arch/arm/mach-imx/Kconfig** of the u-boot-imx [repo](https://github.com/nxp-imx/uboot-imx) (branch: lf_v2024.04).

**Comment by otavio** [comment]
Can you rebase the patch and send a PR to fix that?

**Comment by JSmitNortech** [comment]
I am attempting to implement a fix. However, I am not YOCTO expert. 

I am currently using this layer to build the Mender image for the Olimex iMX8M Plus dev board ([meta-mender-community](https://github.com/mendersoftware/meta-mender-community)), which implements its own changes to the u-boot-imx recipe. Is there a way I can test the u-boot-imx recipe compilation without the changes that the meta-mender-community layer implements?

**Comment by otavio** [comment]
Absolutely, You just need to remove the layer from the bblayers file.

**Comment by JSmitNortech** [comment]
I managed to update the patch locally and it is currently applying successfully. However, the compilation step fails with this error:

**| /usr/src/debug/u-boot-imx/2024.04/drivers/usb/gadget/f_mass_storage.c:688:(.text.sleep_thread.lto_priv.0+0xf0): undefined reference to `dm_usb_gadget_handle_interrupts'**

Digging through the compilation logs, it seems this function is undefined at various points in the u-boot-imx codebase. However, I only get this error when building for the Olimex board. Using the same layers for a standards imx8mp-evk build does not yield these errors. So I believe there is likely a configuration issue for the Olimex imx8mp dev board.

**Comment by otavio** [comment]
Yes, probably the USB gadget support needs to be enabled.

**Comment by leon-anavi** [comment]
> @leon-anavi has a draft PR that enables "CONFIG_DM_USB_GADGET"
> 
> #307

Actually, CONFIG_DM_USB_GADGET is not needed. I rebased the patch.

I fixed this issues and I opened a GitHub PR for branch master: https://github.com/Freescale/meta-freescale-3rdparty/pull/308

**Comment by JSmitNortech** [comment]
Thank you for the assistance @leon-anavi. I'll close this issue as it seems like it is now resolved.

**Comment by leon-anavi** [comment]
> Thank you for the assistance @leon-anavi. I'll close this issue as it seems like it is now resolved.

My pleasure, please ping me in any related to this board GitHub issues. I have the hardware and I can assist. Btw I have also ported Mender and RAUC as software update solutions for Olimex i.MX8MP SoM and evaluation board.

Best regards, Leon
