### ISSUE TITLE
machine colibri_vf.conf: SERIAL_CONSOLE not set

### ISSUE THREAD

**Issue by prof7bit** [Freescale/meta-freescale-3rdparty#5]
When using this machine then it ends up using the wrong serial console in the inittab, making it impossible to log in on the UART console, it would instead try to spawn a getty on a non-existing interface from meta-freescale's imx-base.inc which is `SERIAL_CONSOLE = "115200 ttymxc0"` and takes precedence. Such a device does not exist on the colibri machine with the linux-toradex kernel. 

It seems I can make it behave correctly if I replace the assignment of SERIAL_CONSOLE in the machine  conf:

```
diff --git a/conf/machine/colibri-vf.conf b/conf/machine/colibri-vf.conf
index 3ddef79..ba47488 100644
--- a/conf/machine/colibri-vf.conf
+++ b/conf/machine/colibri-vf.conf
@@ -35,6 +35,6 @@ MKUBIFS_ARGS = " -c 8112 -e 124KiB -m 2KiB -F"
 UBINIZE_ARGS = " -p 128KiB -m 2048 -s 2048"
 UBI_VOLNAME = "rootfs"

-SERIAL_CONSOLE ?= "115200 ttyLP0"
+SERIAL_CONSOLE = "115200 ttyLP0"

 MACHINE_FEATURES += "usbgadget usbhost vfat alsa touchscreen"
```

**Comment by otavio** [comment]
You're right; do you mind preparing a patch to fix this?

**Comment by prof7bit** [comment]
I submitted a pull request (#6) that would close this issue when merged.

**Comment by prof7bit** [comment]
the patch is actually already in the first post of this issue, you can just apply it.
