### ISSUE TITLE
Variscite uboot and kernel recipes missing compiler-gcc7.h file

### ISSUE THREAD

**Issue by dellgreen** [Freescale/meta-freescale-3rdparty#7]
Some of the other 3rd party boards have compiler-gcc7.h and compiler-gcc6.h files.
The variciste recipes have compiler-gcc6.h but are missing compiler-gcc7.h.
This results in not being able to compile uboot and kernel for variscite boards using poky sumo branch

**Comment by otavio** [comment]
I am closing this as no PR has been made and it is clearly inactive.
