### ISSUE TITLE
FSLC: colibri-imx7-emmc does not build

### ISSUE THREAD

**Issue by Domarys** [Freescale/meta-freescale-3rdparty#78]
During the build time of a core-image-minimal image the following errors appeared:

```
ERROR: Nothing PROVIDES 'virtual/kernel'
ERROR: Required build target 'core-image-minimal' has no buildable providers
```

**Comment by MaxKrummenacher** [comment]
Hi

It is related to the recent change to default to `use-mainline-bsp`.
I'll send a patch.

Max
